# Generated by Django 5.2.18 on 2026-10-07 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_kinds', models.JSONField(blank=True, default=list)),
                ('reminder_enabled', models.BooleanField(default=False, verbose_name='remind before lessons')),
                ('reminder_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='minutes before')),
                ('daily_digest_enabled', models.BooleanField(default=False, verbose_name='evening summary')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification settings',
                'verbose_name_plural': 'notification settings',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=1000, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'push subscription',
                'verbose_name_plural': 'push subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('room_changed', 'Lesson moved to another room'), ('time_changed', 'Lesson moved to another time'), ('cancelled', 'Lesson cancelled'), ('teacher_changed', 'Teacher replaced'), ('lesson_added', 'New lesson added'), ('link_changed', 'Online lesson link changed'), ('schedule_published', 'New timetable published'), ('reminder', 'Lesson reminder'), ('daily_digest', "Tomorrow's lessons"), ('request_answered', 'Reschedule request answered')], max_length=30)),
                ('params', models.JSONField(default=dict)),
                ('language', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='dispatcher comment')),
                ('dedup_key', models.CharField(max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.schedulechange')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.scheduleentry')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedup_key'), name='notification_dedup')],
            },
        ),
    ]
