# Generated by Django 5.2.18 on 2026-10-07 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolverRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(default='cpsat', max_length=30, verbose_name='algorithm')),
                ('params', models.JSONField(default=dict, verbose_name='parameters')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Finished'), ('infeasible', 'No solution'), ('failed', 'Error'), ('cancelled', 'Cancelled')], default='queued', max_length=12)),
                ('progress', models.JSONField(default=dict)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('objective', models.FloatField(blank=True, null=True)),
                ('best_bound', models.FloatField(blank=True, null=True)),
                ('lessons_total', models.PositiveIntegerField(default=0)),
                ('lessons_placed', models.PositiveIntegerField(default=0)),
                ('hard_violations', models.PositiveIntegerField(default=0)),
                ('soft_violations', models.JSONField(default=dict)),
                ('diagnostics', models.JSONField(default=list)),
                ('model_stats', models.JSONField(default=dict)),
                ('base_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.schedule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.faculty')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.educationform')),
                ('result_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solver_runs', to='scheduling.schedule')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_runs', to='academics.semester')),
            ],
            options={
                'verbose_name': 'automatic scheduling run',
                'verbose_name_plural': 'automatic scheduling runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
