"""Demo data for `manage.py seed_demo`. All people, IDs and codes are fictional samples."""

from datetime import date, time

# (uz, ru, en)
ACADEMY = (
    "O'zbekiston Xalqaro Islomshunoslik Akademiyasi",
    "Международная академия исламоведения Узбекистана",
    "International Academy of Islamic Studies of Uzbekistan",
)

FACULTIES = {
    "ISL": (
        ("Islomshunoslik fakulteti", "Факультет исламоведения", "Faculty of Islamic Studies"),
        "uz",
    ),
    "RUS": (
        (
            "Rus tilida ta'lim fakulteti",
            "Факультет обучения на русском языке",
            "Faculty of Russian-Medium Education",
        ),
        "ru",
    ),
}

DEPARTMENTS = {
    "QH": (
        "ISL",
        (
            "Qur'onshunoslik va hadisshunoslik kafedrasi",
            "Кафедра корановедения и хадисоведения",
            "Department of Quranic and Hadith Studies",
        ),
    ),
    "FA": (
        "ISL",
        (
            "Islom huquqi (fiqh) va aqida kafedrasi",
            "Кафедра исламского права (фикх) и акиды",
            "Department of Islamic Law (Fiqh) and Aqidah",
        ),
    ),
    "IGT": (
        "ISL",
        (
            "Ijtimoiy-gumanitar fanlar va tillar kafedrasi",
            "Кафедра социально-гуманитарных наук и языков",
            "Department of Social Sciences, Humanities and Languages",
        ),
    ),
    "RIS": (
        "RUS",
        (
            "Islomshunoslik va ijtimoiy fanlar kafedrasi",
            "Кафедра исламоведения и социальных наук",
            "Department of Islamic and Social Studies",
        ),
    ),
}

LEVELS = {
    "bachelor": ("Bakalavriat", "Бакалавриат", "Bachelor's degree"),
    "master": ("Magistratura", "Магистратура", "Master's degree"),
}

# code: (names, schedule_mode, requires_room, max_lessons_per_day, study_weekdays)
FORMS = {
    "kunduzgi": (("Kunduzgi", "Очная", "Full-time"), "weekly", True, 4, [0, 1, 2, 3, 4, 5]),
    "kechki": (("Kechki", "Вечерняя", "Evening"), "weekly", True, 2, [0, 1, 2, 3, 4]),
    "sirtqi": (
        ("Sirtqi", "Заочная", "Part-time (correspondence)"),
        "session",
        True,
        4,
        [0, 1, 2, 3, 4, 5],
    ),
    "masofaviy": (
        ("Masofaviy", "Дистанционная", "Distance"),
        "weekly",
        False,
        2,
        [0, 1, 2, 3, 4, 5],
    ),
}

# form: [(number, start, end, shift)]
LESSON_TIMES = {
    "kunduzgi": [
        (1, time(8, 30), time(9, 50), 1),
        (2, time(10, 0), time(11, 20), 1),
        (3, time(11, 30), time(12, 50), 1),
        (4, time(13, 30), time(14, 50), 2),
        (5, time(15, 0), time(16, 20), 2),
        (6, time(16, 30), time(17, 50), 2),
    ],
    "kechki": [(1, time(18, 0), time(19, 20), 1), (2, time(19, 30), time(20, 50), 1)],
    "masofaviy": [(1, time(18, 30), time(19, 50), 1), (2, time(20, 0), time(21, 20), 1)],
}
LESSON_TIMES["sirtqi"] = LESSON_TIMES["kunduzgi"]

BLOCKED = [
    # (names, weekday, start, end, is_hard)
    (("Juma namozi", "Пятничная молитва", "Friday prayer"), 4, time(12, 0), time(14, 0), True),
    (
        ("Asr namozi tanaffusi", "Перерыв на аср-намаз", "Asr prayer break"),
        None,
        time(15, 0),
        time(16, 20),
        False,
    ),
]

ROOM_TYPES = {
    "lecture_hall": ("Ma'ruza zali", "Лекционный зал", "Lecture hall"),
    "auditorium": ("Auditoriya", "Аудитория", "Classroom"),
    "computer": ("Kompyuter xona", "Компьютерный класс", "Computer lab"),
    "linguaphone": ("Lingafon xona", "Лингафонный кабинет", "Language lab"),
    "gym": ("Sport zal", "Спортивный зал", "Gym"),
}

LESSON_TYPES = {
    # code: (names, default room type)
    "lecture": (("Ma'ruza", "Лекция", "Lecture"), None),
    "practice": (("Amaliy mashg'ulot", "Практическое занятие", "Practical class"), None),
    "seminar": (("Seminar", "Семинар", "Seminar"), None),
    "lab": (("Laboratoriya", "Лабораторная работа", "Laboratory"), "computer"),
}

BUILDINGS = {
    "A": ("A bino", "Корпус A", "Building A"),
    "B": ("B bino", "Корпус B", "Building B"),
}

# (building, name, floor, type, capacity, projector, computers)
ROOMS = [
    ("A", "Ma'ruza zali 1", 1, "lecture_hall", 150, True, 0),
    ("A", "Ma'ruza zali 2", 1, "lecture_hall", 90, True, 0),
    ("A", "Ma'ruza zali 3", 2, "lecture_hall", 120, True, 0),
    ("A", "A-105", 1, "auditorium", 30, False, 0),
    ("A", "A-108", 1, "auditorium", 32, True, 0),
    ("A", "A-112", 1, "auditorium", 28, False, 0),
    ("A", "A-115", 1, "auditorium", 36, True, 0),
    ("A", "A-201", 2, "auditorium", 30, False, 0),
    ("A", "A-204", 2, "auditorium", 34, True, 0),
    ("A", "A-207", 2, "auditorium", 25, False, 0),
    ("A", "A-210", 2, "auditorium", 36, True, 0),
    ("A", "A-213", 2, "auditorium", 30, False, 0),
    ("A", "A-301", 3, "auditorium", 40, True, 0),
    ("A", "A-302", 3, "auditorium", 26, False, 0),
    ("A", "A-304", 3, "auditorium", 30, False, 0),
    ("B", "B-104", 1, "auditorium", 30, False, 0),
    ("B", "B-108", 1, "auditorium", 28, False, 0),
    ("B", "B-112", 1, "auditorium", 30, True, 0),
    ("B", "B-114", 1, "auditorium", 32, False, 0),
    ("B", "B-201", 2, "auditorium", 35, True, 0),
    ("B", "B-205", 2, "auditorium", 25, False, 0),
    ("B", "B-305", 3, "auditorium", 30, True, 0),
    ("B", "B-308", 3, "auditorium", 40, True, 0),
    ("B", "Kompyuter xona 1", 2, "computer", 25, True, 25),
    ("B", "Kompyuter xona 2", 3, "computer", 30, True, 30),
    ("B", "Lingafon xona 1", 2, "linguaphone", 16, True, 16),
    ("B", "Lingafon xona 2", 2, "linguaphone", 16, True, 16),
    ("B", "Sport zal", 1, "gym", 60, False, 0),
]

# code: (names, department, is_language, practice room type)
SUBJECTS = {
    "QUR": (
        ("Qur'on o'qish va tajvid", "Чтение Корана и таджвид", "Quran Recitation and Tajweed"),
        "QH",
        False,
        None,
    ),
    "TAF": (("Tafsir", "Тафсир", "Tafsir"), "QH", False, None),
    "HAD": (("Hadis ilmi", "Хадисоведение", "Hadith Studies"), "QH", False, None),
    "MUS": (("Mustalah al-hadis", "Мусталах аль-хадис", "Mustalah al-Hadith"), "QH", False, None),
    "FIQ": (("Fiqh", "Фикх", "Fiqh"), "FA", False, None),
    "USF": (("Usul al-fiqh", "Усуль аль-фикх", "Usul al-Fiqh"), "FA", False, None),
    "AQI": (("Aqida", "Акида", "Aqidah"), "FA", False, None),
    "KAL": (("Kalom ilmi", "Калам", "Kalam"), "FA", False, None),
    "TAS": (("Tasavvuf tarixi", "История суфизма", "History of Sufism"), "FA", False, None),
    "IQT": (
        (
            "Islom iqtisodiyoti asoslari",
            "Основы исламской экономики",
            "Fundamentals of Islamic Economics",
        ),
        "FA",
        False,
        None,
    ),
    "TAR": (("Islom tarixi", "История ислама", "History of Islam"), "IGT", False, None),
    "QDS": (
        ("Qiyosiy dinshunoslik", "Сравнительное религиоведение", "Comparative Religion"),
        "IGT",
        False,
        None,
    ),
    "ARB": (("Arab tili", "Арабский язык", "Arabic Language"), "IGT", True, None),
    "ARA": (("Arab adabiyoti", "Арабская литература", "Arabic Literature"), "IGT", False, None),
    "ENG": (("Ingliz tili", "Английский язык", "English Language"), "IGT", True, None),
    "UZT": (
        ("O'zbekiston tarixi", "История Узбекистана", "History of Uzbekistan"),
        "IGT",
        False,
        None,
    ),
    "FAL": (("Falsafa", "Философия", "Philosophy"), "IGT", False, None),
    "MAN": (("Mantiq", "Логика", "Logic"), "IGT", False, None),
    "AXT": (
        ("Axborot texnologiyalari", "Информационные технологии", "Information Technology"),
        "IGT",
        False,
        "computer",
    ),
    "UZL": (("O'zbek tili", "Узбекский язык", "Uzbek Language"), "RIS", True, None),
}

# (faculty, level, code, names)
PROGRAMS = {
    "IS": ("ISL", "bachelor", "60220300", ("Islomshunoslik", "Исламоведение", "Islamic Studies")),
    "DSH": ("ISL", "bachelor", "60221600", ("Dinshunoslik", "Религиоведение", "Religious Studies")),
    "ISM": ("ISL", "master", "70220301", ("Islomshunoslik", "Исламоведение", "Islamic Studies")),
    "ISR": ("RUS", "bachelor", "60220300", ("Islomshunoslik", "Исламоведение", "Islamic Studies")),
}

# (program, form, duration years, group prefix)
PROGRAM_FORMS = [
    ("IS", "kunduzgi", "4", "IS"),
    ("IS", "kechki", "4.5", "IS-K"),
    ("IS", "sirtqi", "5", "IS-S"),
    ("IS", "masofaviy", "5", "IS-M"),
    ("DSH", "kunduzgi", "4", "DSH"),
    ("ISM", "kunduzgi", "2", "IS-MG"),
    ("ISR", "kunduzgi", "4", "IS-R"),
    ("ISR", "sirtqi", "5", "IS-RS"),
]

# (program, form, course, number, language, students, composition, shift)
GROUPS = [
    ("IS", "kunduzgi", 1, 1, "uz", 26, "male", 1),
    ("IS", "kunduzgi", 1, 2, "uz", 25, "female", 1),
    ("IS", "kunduzgi", 2, 1, "uz", 24, "male", 2),
    ("IS", "kunduzgi", 2, 2, "uz", 23, "female", 2),
    ("IS", "kunduzgi", 3, 1, "uz", 27, "mixed", 1),
    ("IS", "kunduzgi", 3, 2, "uz", 27, "mixed", 1),
    ("IS", "kunduzgi", 4, 1, "uz", 22, "male", 2),
    ("IS", "kunduzgi", 4, 2, "uz", 24, "female", 2),
    ("DSH", "kunduzgi", 1, 1, "uz", 28, "mixed", 1),
    ("DSH", "kunduzgi", 2, 1, "uz", 25, "mixed", 2),
    ("DSH", "kunduzgi", 3, 1, "uz", 24, "mixed", 1),
    ("DSH", "kunduzgi", 4, 1, "uz", 22, "mixed", 2),
    ("IS", "kechki", 2, 1, "uz", 20, "mixed", 1),
    ("IS", "kechki", 3, 1, "uz", 18, "mixed", 1),
    ("IS", "sirtqi", 1, 1, "uz", 32, "mixed", 1),
    ("IS", "sirtqi", 2, 1, "uz", 28, "mixed", 1),
    ("IS", "sirtqi", 3, 1, "uz", 26, "mixed", 1),
    ("IS", "masofaviy", 1, 1, "uz", 22, "mixed", 1),
    ("IS", "masofaviy", 2, 1, "uz", 20, "mixed", 1),
    ("ISM", "kunduzgi", 1, 1, "uz", 12, "mixed", 2),
    ("ISR", "kunduzgi", 1, 1, "ru", 22, "mixed", 1),
    ("ISR", "kunduzgi", 2, 1, "ru", 20, "mixed", 2),
    ("ISR", "kunduzgi", 2, 2, "ru", 19, "mixed", 2),
    ("ISR", "kunduzgi", 3, 1, "ru", 21, "mixed", 1),
    ("ISR", "kunduzgi", 4, 1, "ru", 18, "mixed", 2),
    ("ISR", "sirtqi", 2, 1, "ru", 22, "mixed", 1),
]

# Lectures of these group pairs are read together: (name, groups, subjects with joint lectures)
STREAMS = [
    ("IS-101 + IS-102", ["IS-101", "IS-102"], None),
    ("IS-201 + IS-202", ["IS-201", "IS-202"], None),
    ("IS-301 + IS-302", ["IS-301", "IS-302"], ["TAF", "HAD", "FIQ", "TAR", "MAN"]),
    ("IS-401 + IS-402", ["IS-401", "IS-402"], None),
    ("IS-R-201 + IS-R-202", ["IS-R-201", "IS-R-202"], None),
]

# Subjects whose practice/lab is split into two subgroups (per study semester).
SPLIT = {
    ("ENG", "practice"): {2, 4},
    ("AXT", "lab"): {2},
}

# Curriculum. Weekly forms: lessons per week by type (L, P, S, B=lab).
# Session forms: classroom hours by type; credits explicit.
WEEKLY_PLANS = {
    ("IS", "kunduzgi", ""): {
        2: {
            "QUR": "P2",
            "ARB": "P3",
            "ENG": "P2",
            "UZT": "L1 S1",
            "FAL": "L1 S1",
            "AXT": "L1 B1",
            "AQI": "L1 S1",
        },
        4: {
            "TAF": "L1 S1",
            "MUS": "L1 S1",
            "FIQ": "L1 S1",
            "ARB": "P3",
            "ENG": "P2",
            "QDS": "L1 S1",
        },
        6: {
            "TAF": "L1 S1",
            "HAD": "L1 S1",
            "FIQ": "L1 S1",
            "AQI": "L1 S1",
            "TAR": "L1 S1",
            "ARB": "P3",
            "ENG": "P2",
            "AXT": "B1",
            "MAN": "L1",
        },
        8: {
            "USF": "L1 S1",
            "KAL": "L1 S1",
            "TAS": "L1 S1",
            "ARA": "L1 P1",
            "IQT": "L1 S1",
            "ARB": "P2",
        },
    },
    ("DSH", "kunduzgi", ""): {
        2: {
            "QDS": "L1 S1",
            "FAL": "L1 S1",
            "UZT": "L1 S1",
            "ARB": "P2",
            "ENG": "P2",
            "AXT": "L1 B1",
        },
        4: {"QDS": "L1 S1", "TAR": "L1 S1", "MAN": "L1 S1", "ARB": "P2", "ENG": "P2", "AQI": "L1"},
        6: {
            "QDS": "L1 S1",
            "TAS": "L1 S1",
            "KAL": "L1 S1",
            "FAL": "L1 S1",
            "ENG": "P2",
            "ARB": "P2",
        },
        8: {"QDS": "L1 S1", "IQT": "L1 S1", "TAR": "L1 S1", "USF": "L1"},
    },
    ("IS", "kechki", ""): {
        4: {"TAF": "L1", "FIQ": "L1 S1", "ARB": "P2", "ENG": "P1", "MUS": "L1"},
        6: {"HAD": "L1 S1", "AQI": "L1", "TAR": "L1", "ARB": "P2", "MAN": "L1"},
    },
    ("IS", "masofaviy", ""): {
        2: {"QUR": "P1", "ARB": "P2", "AQI": "L1", "UZT": "L1", "FAL": "L1"},
        4: {"TAF": "L1", "FIQ": "L1", "MUS": "L1", "ARB": "P2", "ENG": "P1"},
    },
    ("ISM", "kunduzgi", ""): {
        2: {"TAF": "L1 S1", "USF": "L1 S1", "HAD": "L1 S1", "KAL": "L1"},
    },
    ("ISR", "kunduzgi", "ru"): {
        2: {"QUR": "P2", "ARB": "P3", "UZL": "P2", "AQI": "L1 S1", "FAL": "L1 S1", "AXT": "L1 B1"},
        4: {"TAF": "L1 S1", "FIQ": "L1 S1", "MUS": "L1 S1", "ARB": "P3", "UZL": "P2"},
        6: {"HAD": "L1 S1", "AQI": "L1 S1", "TAR": "L1 S1", "ARB": "P3", "MAN": "L1"},
        8: {"USF": "L1 S1", "KAL": "L1 S1", "IQT": "L1 S1"},
    },
}

SESSION_PLANS = {
    ("IS", "sirtqi", ""): {
        2: {
            "QUR": ("P8", 4),
            "ARB": ("P12", 6),
            "AQI": ("L8 S4", 4),
            "UZT": ("L8 S4", 4),
            "FAL": ("L8 S4", 4),
        },
        4: {
            "TAF": ("L8 S4", 4),
            "FIQ": ("L8 S4", 4),
            "MUS": ("L8 S4", 4),
            "ARB": ("P12", 6),
            "ENG": ("P8", 4),
        },
        6: {
            "HAD": ("L8 S4", 4),
            "AQI": ("L8 S4", 4),
            "TAR": ("L8 S4", 4),
            "ARB": ("P12", 6),
            "MAN": ("L8", 2),
        },
    },
    ("ISR", "sirtqi", "ru"): {
        4: {"TAF": ("L8 S4", 4), "FIQ": ("L8 S4", 4), "ARB": ("P12", 6), "UZL": ("P8", 4)},
    },
}

# (last, first, middle, dept, position, degree, employment, annual hours, max/week, subjects, languages)
TEACHERS = [
    (
        "Yusupov",
        "Sardor",
        "Akmalovich",
        "QH",
        "associate_professor",
        "phd",
        "staff",
        900,
        16,
        ["TAF", "QUR"],
        ["uz", "ar"],
    ),
    (
        "Karimov",
        "Bahodir",
        "Rustamovich",
        "QH",
        "associate_professor",
        "phd",
        "staff",
        900,
        16,
        ["HAD", "MUS"],
        ["uz", "ar"],
    ),
    (
        "Xolmatov",
        "Ilhom",
        "Erkinovich",
        "QH",
        "senior_teacher",
        "none",
        "staff",
        950,
        18,
        ["QUR", "TAF", "MUS"],
        ["uz", "ru", "ar"],
    ),
    (
        "Olimov",
        "Jasur",
        "Baxtiyorovich",
        "QH",
        "assistant",
        "none",
        "staff",
        950,
        18,
        ["QUR", "HAD"],
        ["uz"],
    ),
    (
        "Ibragimov",
        "Shavkat",
        "Nematovich",
        "QH",
        "professor",
        "dsc",
        "staff",
        700,
        12,
        ["TAF", "HAD", "MUS"],
        ["uz", "ru", "ar"],
    ),
    (
        "Sultonova",
        "Nilufar",
        "Rashidovna",
        "QH",
        "teacher",
        "none",
        "staff",
        950,
        18,
        ["QUR", "MUS"],
        ["uz", "ru"],
    ),
    (
        "Rahimov",
        "Dilshod",
        "Toxirovich",
        "FA",
        "associate_professor",
        "phd",
        "staff",
        900,
        16,
        ["FIQ", "USF"],
        ["uz", "ar"],
    ),
    (
        "Mirzayev",
        "Hasan",
        "Ilyosovich",
        "FA",
        "senior_teacher",
        "none",
        "staff",
        950,
        18,
        ["AQI", "KAL"],
        ["uz", "ar"],
    ),
    (
        "Ergashev",
        "Komil",
        "Saidovich",
        "FA",
        "professor",
        "dsc",
        "staff",
        700,
        12,
        ["USF", "FIQ", "IQT"],
        ["uz", "ru"],
    ),
    (
        "Hasanova",
        "Dilnoza",
        "Alisherovna",
        "FA",
        "teacher",
        "none",
        "staff",
        950,
        18,
        ["AQI", "TAS", "FIQ"],
        ["uz", "ru"],
    ),
    (
        "Nurmatov",
        "Bekzod",
        "Olimjonovich",
        "FA",
        "assistant",
        "none",
        "part_time",
        450,
        10,
        ["IQT", "FIQ"],
        ["uz"],
    ),
    (
        "Tursunov",
        "Alisher",
        "Qahramonovich",
        "FA",
        "associate_professor",
        "phd",
        "staff",
        900,
        16,
        ["KAL", "TAS", "AQI"],
        ["uz", "ru", "ar"],
    ),
    (
        "Abdullayev",
        "Anvar",
        "Mahmudovich",
        "IGT",
        "teacher",
        "none",
        "staff",
        1000,
        18,
        ["ARB"],
        ["uz", "ar"],
    ),
    (
        "Nazarova",
        "Malika",
        "Bahromovna",
        "IGT",
        "senior_teacher",
        "none",
        "staff",
        950,
        18,
        ["ENG"],
        ["uz", "en", "ru"],
    ),
    (
        "Toshmatov",
        "Umid",
        "Shuhratovich",
        "IGT",
        "associate_professor",
        "phd",
        "staff",
        900,
        16,
        ["TAR", "UZT"],
        ["uz", "ru"],
    ),
    (
        "Qodirov",
        "Jamshid",
        "Anvarovich",
        "IGT",
        "senior_teacher",
        "none",
        "staff",
        950,
        18,
        ["AXT"],
        ["uz", "ru"],
    ),
    (
        "Saidov",
        "Farrux",
        "Ulug'bekovich",
        "IGT",
        "associate_professor",
        "phd",
        "staff",
        900,
        16,
        ["MAN", "FAL"],
        ["uz", "ru"],
    ),
    (
        "Zokirov",
        "Otabek",
        "Jo'rayevich",
        "IGT",
        "teacher",
        "none",
        "staff",
        1000,
        18,
        ["ARB", "ARA"],
        ["uz", "ar", "ru"],
    ),
    (
        "Rasulova",
        "Kamola",
        "Ibrohimovna",
        "IGT",
        "teacher",
        "none",
        "staff",
        1000,
        18,
        ["ARB"],
        ["uz", "ar"],
    ),
    (
        "Umarov",
        "Shoxrux",
        "Zafarovich",
        "IGT",
        "assistant",
        "none",
        "part_time",
        500,
        12,
        ["ARB"],
        ["uz", "ru", "ar"],
    ),
    (
        "Aliyeva",
        "Gulnora",
        "Farhodovna",
        "IGT",
        "teacher",
        "none",
        "staff",
        950,
        18,
        ["ENG"],
        ["uz", "en"],
    ),
    (
        "Ismoilova",
        "Feruza",
        "Baxodirovna",
        "IGT",
        "teacher",
        "none",
        "staff",
        950,
        18,
        ["ENG"],
        ["uz", "en", "ru"],
    ),
    (
        "Yo'ldoshev",
        "Sanjar",
        "Botirovich",
        "IGT",
        "associate_professor",
        "phd",
        "staff",
        900,
        16,
        ["FAL", "QDS"],
        ["uz", "ru"],
    ),
    (
        "Normatova",
        "Shahlo",
        "Ravshanovna",
        "IGT",
        "senior_teacher",
        "none",
        "staff",
        950,
        18,
        ["QDS", "TAR"],
        ["uz"],
    ),
    (
        "Bakirov",
        "Rustam",
        "Valiyevich",
        "IGT",
        "teacher",
        "none",
        "hourly",
        300,
        8,
        ["AXT"],
        ["uz", "ru"],
    ),
    (
        "Haydarov",
        "Nodir",
        "Sobirovich",
        "IGT",
        "teacher",
        "none",
        "staff",
        950,
        18,
        ["UZT", "TAR", "MAN"],
        ["uz"],
    ),
    (
        "Ahmedova",
        "Lola",
        "Karimovna",
        "IGT",
        "teacher",
        "none",
        "staff",
        1000,
        18,
        ["ARA", "ARB"],
        ["uz", "ar"],
    ),
    (
        "Mamatqulov",
        "Sherzod",
        "Normurodovich",
        "IGT",
        "assistant",
        "none",
        "part_time",
        500,
        12,
        ["ARB"],
        ["uz", "ru", "ar"],
    ),
    (
        "Xudoyberdiyeva",
        "Zarina",
        "Akramovna",
        "RIS",
        "teacher",
        "none",
        "staff",
        950,
        18,
        ["UZL"],
        ["ru", "uz"],
    ),
    (
        "Ахмедов",
        "Тимур",
        "Рашидович",
        "RIS",
        "associate_professor",
        "phd",
        "staff",
        900,
        16,
        ["TAR", "FAL", "MAN", "QDS"],
        ["ru"],
    ),
    (
        "Соколова",
        "Ирина",
        "Павловна",
        "RIS",
        "senior_teacher",
        "none",
        "staff",
        950,
        18,
        ["ENG", "AXT"],
        ["ru", "en"],
    ),
    (
        "Шарипов",
        "Руслан",
        "Ильдарович",
        "RIS",
        "teacher",
        "none",
        "staff",
        1000,
        18,
        ["ARB", "QUR", "AQI"],
        ["ru", "ar"],
    ),
    (
        "Латыпова",
        "Динара",
        "Маратовна",
        "RIS",
        "senior_teacher",
        "phd",
        "staff",
        950,
        18,
        ["FIQ", "HAD", "TAF", "MUS", "AQI"],
        ["ru"],
    ),
]

# Teacher availability: (last name, weekday, lesson number or None, level)
AVAILABILITY = [
    *[("Abdullayev", d, None, "preferred") for d in (0, 1, 2, 3)],
    ("Nurmatov", 0, None, "unavailable"),  # part-time: works elsewhere on Mondays
    ("Nurmatov", 1, None, "unavailable"),
    ("Umarov", 5, None, "unavailable"),
    ("Mamatqulov", 3, None, "unavailable"),
    ("Bakirov", 2, None, "unavailable"),
    ("Bakirov", 4, None, "unavailable"),
    ("Ibragimov", 5, None, "unavailable"),
    ("Ergashev", 0, 1, "unavailable"),
    *[("Yusupov", d, None, "preferred") for d in (0, 1, 2)],
    ("Saidov", 5, None, "preferred"),
]

# IS-301 week exactly as in the mobile design. Lectures marked "S" are stream lectures
# with IS-302. (weekday, lesson, subject, type, room, teacher, target)
IS301_WEEK = [
    (0, 1, "TAF", "lecture", "Ma'ruza zali 1", "Yusupov", "stream"),
    (0, 2, "TAF", "seminar", "A-204", "Yusupov", "group"),
    (0, 3, "ARB", "practice", "B-112", "Abdullayev", "group"),
    (1, 1, "HAD", "lecture", "Ma'ruza zali 2", "Karimov", "stream"),
    (1, 2, "HAD", "seminar", "A-210", "Karimov", "group"),
    (1, 3, "FIQ", "lecture", "Ma'ruza zali 1", "Rahimov", "stream"),
    (1, 4, "ENG", "practice", "B-305", "Nazarova", "group"),
    (2, 1, "ARB", "practice", "B-112", "Abdullayev", "group"),
    (2, 2, "TAR", "lecture", "Ma'ruza zali 3", "Toshmatov", "stream"),
    (2, 3, "AXT", "lab", "Kompyuter xona 2", "Qodirov", "group"),
    (3, 1, "FIQ", "seminar", "A-210", "Rahimov", "group"),
    (3, 2, "ARB", "practice", "B-112", "Abdullayev", "group"),
    (3, 3, "AQI", "lecture", "A-115", "Mirzayev", "group"),
    (4, 1, "TAR", "seminar", "A-115", "Toshmatov", "group"),
    (4, 2, "AQI", "seminar", "A-115", "Mirzayev", "group"),
    (5, 1, "ENG", "practice", "B-305", "Nazarova", "group"),
    (5, 2, "MAN", "lecture", "Ma'ruza zali 3", "Saidov", "stream"),
]
# Extra pinned lesson from the teacher screen of the design (Abdullayev, Wednesday 11:30).
EXTRA_PINNED = [(2, 3, "IS-102", "ARB", "practice", "B-112", "Abdullayev")]

# Who teaches what is fixed for these (group, subject, lesson type) by the design.
FIXED_TEACHERS = {
    **{("IS-301", subj, lt): t for _wd, _n, subj, lt, _room, t, _target in IS301_WEEK},
    ("IS-102", "ARB", "practice"): "Abdullayev",
}

ACADEMIC_YEAR = ("2025-2026", date(2025, 9, 1), date(2026, 6, 30))
AUTUMN = (date(2025, 9, 1), date(2026, 1, 24))
SPRING = (date(2026, 2, 23), date(2026, 6, 30))
SPRING_WEEKS = 15  # 23 Feb – 6 Jun; design: 6–11 April is week 7
SESSION = ("O'quv-sinov sessiyasi", date(2026, 4, 6), date(2026, 4, 25))

# (date, kind, names, works_as_weekday, is_assumption)
CALENDAR = [
    (
        date(2026, 3, 8),
        "holiday",
        ("Xalqaro xotin-qizlar kuni", "Международный женский день", "International Women's Day"),
        None,
        False,
    ),
    (date(2026, 3, 20), "holiday", ("Ramazon hayiti", "Рамазан хайит", "Eid al-Fitr"), None, True),
    (date(2026, 3, 21), "holiday", ("Navro'z", "Навруз", "Navruz"), None, False),
    (
        date(2026, 5, 9),
        "holiday",
        ("Xotira va qadrlash kuni", "День памяти и почитания", "Day of Remembrance and Honour"),
        None,
        False,
    ),
    (date(2026, 5, 27), "holiday", ("Qurbon hayiti", "Курбан хайит", "Eid al-Adha"), None, True),
]

MALE_FIRST = [
    "Abdulloh",
    "Muhammad",
    "Ahmad",
    "Umar",
    "Ali",
    "Usmon",
    "Bilol",
    "Jasur",
    "Sardor",
    "Javohir",
    "Shohruh",
    "Doniyor",
    "Bekzod",
    "Azizbek",
    "Otabek",
    "Islom",
    "Ibrohim",
    "Yusuf",
    "Mirzo",
    "Sanjar",
    "Asadbek",
    "Diyorbek",
    "Fayzulloh",
    "Hamza",
    "Ismoil",
    "Komil",
    "Laziz",
    "Nodirbek",
    "Ravshan",
    "Temur",
]
FEMALE_FIRST = [
    "Aziza",
    "Madina",
    "Mohinur",
    "Zarina",
    "Shahzoda",
    "Nilufar",
    "Gulnoza",
    "Dilnoza",
    "Sevara",
    "Malika",
    "Maryam",
    "Oysha",
    "Fotima",
    "Hadicha",
    "Zuhra",
    "Robiya",
    "Mubina",
    "Sabina",
    "Muslima",
    "Ruxshona",
    "Kamola",
    "Laylo",
    "Munisa",
    "Nozima",
    "Sitora",
    "Umida",
    "Hilola",
    "Durdona",
    "Feruza",
    "Yulduz",
]
# Male form; female form adds "a" (Karimov → Karimova).
SURNAMES = [
    "Karimov",
    "Yusupov",
    "Rahimov",
    "Abdullayev",
    "Toshmatov",
    "Mirzayev",
    "Qodirov",
    "Saidov",
    "Nazarov",
    "Ismoilov",
    "Ergashev",
    "Xolmatov",
    "Rasulov",
    "Sultonov",
    "Hasanov",
    "Umarov",
    "Tursunov",
    "Aliyev",
    "Olimov",
    "Nurmatov",
    "Usmonov",
    "Jo'rayev",
    "Bakirov",
    "Haydarov",
    "Sharipov",
    "Zokirov",
    "Ahmedov",
    "Sobirov",
    "Valiyev",
    "Qosimov",
    "Fayzullayev",
    "Murodov",
    "Normatov",
    "Ibragimov",
    "Hamidov",
]
RU_MALE_FIRST = [
    "Тимур",
    "Руслан",
    "Артур",
    "Дамир",
    "Рустам",
    "Эльдар",
    "Марат",
    "Самир",
    "Ильяс",
    "Камиль",
    "Ринат",
    "Азамат",
]
RU_FEMALE_FIRST = [
    "Анна",
    "Алина",
    "Камила",
    "Диана",
    "Амина",
    "Эльвира",
    "Лейла",
    "Мадина",
    "Сабина",
    "Ясмина",
    "Регина",
    "Дильноза",
]
RU_SURNAMES = [
    "Ахмедов",
    "Ким",
    "Шарипов",
    "Латыпов",
    "Исмаилов",
    "Каримов",
    "Юсупов",
    "Хасанов",
    "Рахимов",
    "Пак",
    "Мирзаев",
    "Салихов",
    "Абдуллаев",
    "Тен",
    "Назаров",
    "Валиев",
    "Рашидов",
    "Хамидов",
]
UZ_MALE_PATRONYMIC = [
    "Akmal o'g'li",
    "Rustam o'g'li",
    "Botir o'g'li",
    "Ilhom o'g'li",
    "Sherzod o'g'li",
    "Anvar o'g'li",
]
UZ_FEMALE_PATRONYMIC = [
    "Akmal qizi",
    "Rustam qizi",
    "Botir qizi",
    "Ilhom qizi",
    "Sherzod qizi",
    "Anvar qizi",
]

DEMO_PASSWORDS = {
    "admin": "admin123",
    "dekanat": "dekanat123",
    "kafedra": "kafedra123",
    "oqituvchi": "oqituvchi123",
    "talaba": "talaba123",
    "talaba_ru": "talaba123",
}
