# Generated by Django 5.2.18 on 2026-10-07 05:32

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='short name')),
            ],
            options={
                'verbose_name': 'academy',
                'verbose_name_plural': 'academies',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'education level',
                'verbose_name_plural': 'education levels',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'room type',
                'verbose_name_plural': 'room types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicCalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('kind', models.CharField(choices=[('holiday', 'Public holiday'), ('day_off', 'Day off'), ('workday', 'Transferred working day')], max_length=10, verbose_name='type')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('works_as_weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For transferred working days: whose timetable is followed.', null=True, verbose_name='works as weekday')),
                ('is_assumption', models.BooleanField(default=False, help_text='E.g. Eid dates depend on the lunar calendar and must be confirmed.', verbose_name='date is an estimate')),
            ],
            options={
                'verbose_name': 'calendar day',
                'verbose_name_plural': 'academic calendar',
                'ordering': ['date'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'workday'), ('works_as_weekday__isnull', False)), models.Q(models.Q(('kind', 'workday'), _negated=True), ('works_as_weekday__isnull', True)), _connector='OR'), name='calendar_workday_weekday')],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
            ],
            options={
                'verbose_name': 'academic year',
                'verbose_name_plural': 'academic years',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='year_dates_order')],
            },
        ),
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('schedule_mode', models.CharField(choices=[('weekly', 'Weekly recurring'), ('session', 'Session (fixed dates)')], max_length=10, verbose_name='schedule type')),
                ('requires_room', models.BooleanField(default=True, help_text='Distance learning uses a virtual room link instead.', verbose_name='needs a physical room')),
                ('max_lessons_per_day', models.PositiveSmallIntegerField(default=4, verbose_name='max lessons per day for a group')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'education form',
                'verbose_name_plural': 'education forms',
                'ordering': ['order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('schedule_mode__in', ['weekly', 'session'])), name='form_mode_valid'), models.CheckConstraint(condition=models.Q(('max_lessons_per_day__gte', 1)), name='form_max_lessons_positive')],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('teaching_language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('ar', 'Arabic')], default='uz', max_length=2, verbose_name='main teaching language')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculties', to='academics.academy')),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'faculties',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='academics.faculty')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['faculty__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='lesson number')),
                ('start', models.TimeField(verbose_name='start')),
                ('end', models.TimeField(verbose_name='end')),
                ('shift', models.PositiveSmallIntegerField(default=1, verbose_name='shift')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_times', to='academics.educationform')),
            ],
            options={
                'verbose_name': 'lesson time',
                'verbose_name_plural': 'bell schedule',
                'ordering': ['form__order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='program code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.faculty')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.educationlevel')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ['faculty__code', 'level__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProgramForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_years', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='study duration (years)')),
                ('group_prefix', models.CharField(help_text='Used to build group names, e.g. IS → IS-301.', max_length=20, verbose_name='group name prefix')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.educationform')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='academics.program')),
            ],
            options={
                'verbose_name': 'program form',
                'verbose_name_plural': 'program forms',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('course', models.PositiveSmallIntegerField(verbose_name='year of study')),
                ('number', models.PositiveSmallIntegerField(verbose_name='number within course')),
                ('teaching_language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('ar', 'Arabic')], max_length=2, verbose_name='teaching language')),
                ('student_count', models.PositiveSmallIntegerField(verbose_name='students')),
                ('gender_composition', models.CharField(blank=True, choices=[('mixed', 'Mixed'), ('male', 'Male students'), ('female', 'Female students')], default='', max_length=10, verbose_name='composition')),
                ('shift', models.PositiveSmallIntegerField(default=1, verbose_name='shift')),
                ('program_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.programform')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='room')),
                ('floor', models.SmallIntegerField(default=1, verbose_name='floor')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='seats')),
                ('has_projector', models.BooleanField(default=False, verbose_name='projector')),
                ('computer_count', models.PositiveSmallIntegerField(default=0, verbose_name='computers')),
                ('has_board', models.BooleanField(default=True, verbose_name='board')),
                ('is_active', models.BooleanField(default=True, verbose_name='in use')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='academics.building')),
                ('faculty', models.ForeignKey(blank=True, help_text='Optional: room reserved for a faculty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='academics.faculty')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='academics.roomtype')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ['building__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('lecture', 'Lecture'), ('practice', 'Practical class'), ('seminar', 'Seminar'), ('lab', 'Laboratory')], max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('default_room_type', models.ForeignKey(blank=True, help_text='Room type this kind of lesson needs by default (e.g. lab → computer room).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.roomtype')),
            ],
            options={
                'verbose_name': 'lesson type',
                'verbose_name_plural': 'lesson types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('autumn', 'Autumn semester'), ('spring', 'Spring semester')], max_length=10, verbose_name='semester')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_current', models.BooleanField(default=False, verbose_name='current semester')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'semester',
                'verbose_name_plural': 'semesters',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('teaching_language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('ar', 'Arabic')], max_length=2, verbose_name='teaching language')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='academics.faculty')),
                ('groups', models.ManyToManyField(related_name='streams', to='academics.group')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.semester')),
            ],
            options={
                'verbose_name': 'stream',
                'verbose_name_plural': 'streams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('student_count', models.PositiveSmallIntegerField(verbose_name='students')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='academics.group')),
            ],
            options={
                'verbose_name': 'subgroup',
                'verbose_name_plural': 'subgroups',
                'ordering': ['group__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='patronymic')),
                ('hemis_id', models.CharField(max_length=20, unique=True, verbose_name='HEMIS ID')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='gender')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.group')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.subgroup')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['group__name', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('is_language', models.BooleanField(default=False, help_text='Practice is usually split in subgroups.', verbose_name='language subject')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.department')),
                ('practice_room_type', models.ForeignKey(blank=True, help_text='Room type required for practical/lab lessons of this subject, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.roomtype')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_language', models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('ar', 'Arabic')], default='', max_length=2, verbose_name='teaching language')),
                ('study_semester', models.PositiveSmallIntegerField(verbose_name='study semester')),
                ('credits', models.PositiveSmallIntegerField(verbose_name='credits')),
                ('hours_lecture', models.PositiveSmallIntegerField(default=0, verbose_name='lecture hours')),
                ('hours_practice', models.PositiveSmallIntegerField(default=0, verbose_name='practice hours')),
                ('hours_seminar', models.PositiveSmallIntegerField(default=0, verbose_name='seminar hours')),
                ('hours_lab', models.PositiveSmallIntegerField(default=0, verbose_name='laboratory hours')),
                ('hours_independent', models.PositiveSmallIntegerField(default=0, verbose_name='independent study hours')),
                ('control_type', models.CharField(choices=[('exam', 'Exam'), ('credit', 'Pass/fail test')], max_length=10, verbose_name='assessment')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum', to='academics.educationform')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='academics.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum', to='academics.subject')),
            ],
            options={
                'verbose_name': 'curriculum item',
                'verbose_name_plural': 'curriculum',
                'ordering': ['program', 'form', 'teaching_language', 'study_semester', 'subject__code'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='patronymic')),
                ('position', models.CharField(choices=[('assistant', 'Assistant'), ('teacher', 'Lecturer'), ('senior_teacher', 'Senior lecturer'), ('associate_professor', 'Associate professor'), ('professor', 'Professor')], max_length=30, verbose_name='position')),
                ('degree', models.CharField(choices=[('none', 'No degree'), ('phd', 'PhD'), ('dsc', 'DSc')], default='none', max_length=10, verbose_name='academic degree')),
                ('employment', models.CharField(choices=[('staff', 'Full-time'), ('part_time', 'Part-time (second job)'), ('hourly', 'Hourly')], default='staff', max_length=20, verbose_name='employment')),
                ('annual_load_hours', models.PositiveSmallIntegerField(verbose_name='annual teaching load (hours)')),
                ('max_weekly_lessons', models.PositiveSmallIntegerField(default=18, verbose_name='max lessons per week')),
                ('teaching_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('ar', 'Arabic')], max_length=2), default=list, size=None, verbose_name='teaching languages')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='academics.department')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday')),
                ('level', models.CharField(choices=[('preferred', 'Preferred'), ('possible', 'Possible'), ('unavailable', 'Unavailable')], max_length=12, verbose_name='availability')),
                ('lesson_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.lessontime')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='academics.teacher')),
            ],
            options={
                'verbose_name': 'teacher availability',
                'verbose_name_plural': 'teacher availability',
            },
        ),
        migrations.CreateModel(
            name='TeachingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('weeks_count', models.PositiveSmallIntegerField(blank=True, help_text='Only for weekly forms.', null=True, verbose_name='teaching weeks')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='academics.educationform')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.semester')),
            ],
            options={
                'verbose_name': 'teaching period',
                'verbose_name_plural': 'teaching periods',
                'ordering': ['semester', 'form__order', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_lessons', models.PositiveSmallIntegerField(default=0, verbose_name='lessons every week')),
                ('alternating_lessons', models.PositiveSmallIntegerField(default=0, verbose_name='lessons every other week')),
                ('total_lessons', models.PositiveSmallIntegerField(verbose_name='lessons in the period')),
                ('curriculum_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academics.curriculumitem')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.group')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.lessontype')),
                ('required_room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.roomtype')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.stream')),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.teacher')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.teachingperiod')),
            ],
            options={
                'verbose_name': 'teaching assignment',
                'verbose_name_plural': 'teaching assignments',
            },
        ),
        migrations.CreateModel(
            name='BlockedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Empty means every day.', null=True, verbose_name='weekday')),
                ('start', models.TimeField(verbose_name='start')),
                ('end', models.TimeField(verbose_name='end')),
                ('is_hard', models.BooleanField(default=True, help_text='Strict: never schedule. Otherwise only avoided.', verbose_name='strict')),
                ('form', models.ForeignKey(blank=True, help_text='Empty means all education forms.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='academics.educationform')),
            ],
            options={
                'verbose_name': 'blocked time',
                'verbose_name_plural': 'blocked times',
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='blocked_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='lessontime',
            constraint=models.UniqueConstraint(fields=('form', 'number'), name='lessontime_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='lessontime',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='lessontime_order'),
        ),
        migrations.AddConstraint(
            model_name='lessontime',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='lessontime_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='lessontime',
            constraint=models.CheckConstraint(condition=models.Q(('shift__in', [1, 2])), name='lessontime_shift_valid'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('faculty', 'level', 'code'), name='program_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='programform',
            constraint=models.UniqueConstraint(fields=('program', 'form'), name='programform_unique'),
        ),
        migrations.AddConstraint(
            model_name='programform',
            constraint=models.CheckConstraint(condition=models.Q(('duration_years__gt', 0)), name='programform_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('program_form', 'course', 'number', 'teaching_language'), name='group_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('course__gte', 1), ('course__lte', 6)), name='group_course_range'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('shift__in', [1, 2])), name='group_shift_valid'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('teaching_language__in', ['uz', 'ru', 'en', 'ar'])), name='group_language_valid'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='room_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='room_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('year', 'kind'), name='semester_unique_kind'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='semester_single_current'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='semester_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('semester', 'name'), name='stream_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='subgroup',
            constraint=models.UniqueConstraint(fields=('group', 'number'), name='subgroup_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='subgroup',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 3)), name='subgroup_number_range'),
        ),
        migrations.AddConstraint(
            model_name='curriculumitem',
            constraint=models.UniqueConstraint(fields=('program', 'form', 'teaching_language', 'study_semester', 'subject'), name='curriculum_unique_subject'),
        ),
        migrations.AddConstraint(
            model_name='curriculumitem',
            constraint=models.CheckConstraint(condition=models.Q(('study_semester__gte', 1), ('study_semester__lte', 12)), name='curriculum_semester_range'),
        ),
        migrations.AddConstraint(
            model_name='curriculumitem',
            constraint=models.CheckConstraint(condition=models.Q(('credits__gte', 1)), name='curriculum_credits_positive'),
        ),
        migrations.AddConstraint(
            model_name='curriculumitem',
            constraint=models.CheckConstraint(condition=models.Q(('hours_independent', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('credits'), '*', models.Value(30)), '-', models.F('hours_lecture')), '-', models.F('hours_practice')), '-', models.F('hours_seminar')), '-', models.F('hours_lab')))), name='curriculum_credit_hours'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('teaching_languages__contained_by', ['uz', 'ru', 'en', 'ar']), ('teaching_languages__len__gte', 1)), name='teacher_languages_valid'),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.UniqueConstraint(fields=('teacher', 'weekday', 'lesson_time'), name='availability_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='availability_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='teachingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='period_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='teachingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('weeks_count__isnull', True), ('weeks_count__gte', 1), _connector='OR'), name='period_weeks_positive'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', False), ('stream__isnull', True), ('subgroup__isnull', True)), models.Q(('group__isnull', True), ('stream__isnull', False), ('subgroup__isnull', True)), models.Q(('group__isnull', True), ('stream__isnull', True), ('subgroup__isnull', False)), _connector='OR'), name='assignment_single_target'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.CheckConstraint(condition=models.Q(('total_lessons__gte', 1)), name='assignment_total_positive'),
        ),
    ]
