# Generated by Django 5.2.18 on 2026-10-07 05:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationform',
            name='study_weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='0 = Monday … 6 = Sunday.', size=None, verbose_name='study days'),
        ),
        migrations.AddConstraint(
            model_name='educationform',
            constraint=models.CheckConstraint(condition=models.Q(('study_weekdays__contained_by', [0, 1, 2, 3, 4, 5, 6]), ('study_weekdays__len__gte', 1)), name='form_study_weekdays_valid'),
        ),
    ]
