# Generated by Django 5.2.18 on 2026-10-07 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_educationform_study_weekdays_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedperiod',
            name='form',
            field=models.ForeignKey(blank=True, help_text='Empty means all education forms.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='academics.educationform', verbose_name='education form'),
        ),
        migrations.AlterField(
            model_name='curriculumitem',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum', to='academics.educationform', verbose_name='education form'),
        ),
        migrations.AlterField(
            model_name='curriculumitem',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='academics.program', verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='curriculumitem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum', to='academics.subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='academics.faculty', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculties', to='academics.academy', verbose_name='academy'),
        ),
        migrations.AlterField(
            model_name='group',
            name='program_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.programform', verbose_name='program form'),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_times', to='academics.educationform', verbose_name='education form'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='default_room_type',
            field=models.ForeignKey(blank=True, help_text='Room type this kind of lesson needs by default (e.g. lab → computer room).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.roomtype', verbose_name='default room type'),
        ),
        migrations.AlterField(
            model_name='program',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.faculty', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.educationlevel', verbose_name='education level'),
        ),
        migrations.AlterField(
            model_name='programform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.educationform', verbose_name='education form'),
        ),
        migrations.AlterField(
            model_name='programform',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='academics.program', verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='academics.building', verbose_name='building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Optional: room reserved for a faculty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='academics.faculty', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='academics.roomtype', verbose_name='room type'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear', verbose_name='academic year'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='academics.faculty', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='groups',
            field=models.ManyToManyField(related_name='streams', to='academics.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.semester', verbose_name='semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.subgroup', verbose_name='subgroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='academics.group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practice_room_type',
            field=models.ForeignKey(blank=True, help_text='Room type required for practical/lab lessons of this subject, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.roomtype', verbose_name='room type for practice'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='academics.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject', verbose_name='subjects'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='lesson_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.lessontime', verbose_name='lesson time'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='academics.teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='curriculum_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academics.curriculumitem', verbose_name='curriculum item'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.lessontype', verbose_name='lesson type'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.teachingperiod', verbose_name='teaching period'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='required_room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.roomtype', verbose_name='required room type'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.stream', verbose_name='stream'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subgroup', verbose_name='subgroup'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='teachingperiod',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='academics.educationform', verbose_name='education form'),
        ),
        migrations.AlterField(
            model_name='teachingperiod',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.semester', verbose_name='semester'),
        ),
    ]
