# Generated by Django 5.2.18 on 2026-10-07 05:32

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension, CreateExtension
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # btree_gist: '=' on integer columns inside GiST exclusion constraints;
        # intarray: gist__int_ops for the group-slot array overlap.
        BtreeGistExtension(),
        CreateExtension("intarray"),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived', to='scheduling.schedule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.semester')),
            ],
            options={
                'verbose_name': 'timetable version',
                'verbose_name_plural': 'timetable versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, verbose_name='weekday')),
                ('week_parity', models.CharField(blank=True, choices=[('every', 'Every week'), ('odd', 'Odd weeks'), ('even', 'Even weeks')], max_length=5, null=True, verbose_name='weeks')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('online_url', models.URLField(blank=True, default='', verbose_name='online lesson link')),
                ('is_locked', models.BooleanField(default=False, help_text='Pinned lessons are never moved by the solver.', verbose_name='pinned')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academics.teachingassignment')),
                ('lesson_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.lessontime')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='academics.room')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.schedule')),
            ],
            options={
                'verbose_name': 'timetable entry',
                'verbose_name_plural': 'timetable entries',
            },
        ),
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.UUIDField(db_index=True, verbose_name='change batch')),
                ('action', models.CharField(choices=[('create', 'Lesson added'), ('update', 'Lesson changed'), ('delete', 'Lesson removed'), ('cancel', 'Lesson cancelled')], max_length=10)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('occurrence_date', models.DateField(blank=True, help_text='Set when only one dated lesson is affected.', null=True)),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='scheduling.schedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='scheduling.scheduleentry')),
            ],
            options={
                'verbose_name': 'timetable change',
                'verbose_name_plural': 'timetable changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField(blank=True, help_text='Empty means the lesson every week.', null=True)),
                ('reason', models.TextField(verbose_name='reason')),
                ('desired_weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('desired_date', models.DateField(blank=True, null=True)),
                ('desired_note', models.CharField(blank=True, max_length=255, verbose_name='preferred time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_comment', models.CharField(blank=True, max_length=500, verbose_name='answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('desired_lesson_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.lessontime')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='academics.teacher')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='scheduling.scheduleentry')),
            ],
            options={
                'verbose_name': 'reschedule request',
                'verbose_name_plural': 'reschedule requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('during', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('slot_keys', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('reschedule', 'Needs rescheduling')], default='scheduled', max_length=10)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.teacher')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling.schedule')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='scheduling.scheduleentry')),
            ],
            options={
                'verbose_name': 'lesson occurrence',
                'verbose_name_plural': 'lesson occurrences',
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('semester',), name='schedule_single_published'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'archived'])), name='schedule_status_valid'),
        ),
        migrations.AddIndex(
            model_name='scheduleentry',
            index=models.Index(fields=['schedule', 'weekday', 'lesson_time'], name='scheduling__schedul_ac5d99_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date__isnull', True), ('week_parity__isnull', False), ('weekday__isnull', False)), models.Q(('date__isnull', False), ('week_parity__isnull', True), ('weekday__isnull', True)), _connector='OR'), name='entry_weekly_or_dated'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__isnull', True), models.Q(('weekday__gte', 0), ('weekday__lte', 6)), _connector='OR'), name='entry_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.CheckConstraint(condition=models.Q(('room__isnull', False), models.Q(('online_url', ''), _negated=True), _connector='OR'), name='entry_room_or_link'),
        ),
        migrations.AddIndex(
            model_name='entryoccurrence',
            index=models.Index(fields=['schedule', 'date'], name='scheduling__schedul_4a5507_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryoccurrence',
            constraint=models.UniqueConstraint(fields=('entry', 'date'), name='occurrence_unique_date'),
        ),
        migrations.AddConstraint(
            model_name='entryoccurrence',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'scheduled')), expressions=[('schedule', '='), ('teacher', '='), ('during', '&&')], name='occurrence_no_teacher_overlap'),
        ),
        migrations.AddConstraint(
            model_name='entryoccurrence',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('room__isnull', False), ('status', 'scheduled')), expressions=[('schedule', '='), ('room', '='), ('during', '&&')], name='occurrence_no_room_overlap'),
        ),
        migrations.AddConstraint(
            model_name='entryoccurrence',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'scheduled')), expressions=[('schedule', '='), (django.contrib.postgres.indexes.OpClass(models.F('slot_keys'), name='gist__int_ops'), '&&'), ('during', '&&')], name='occurrence_no_group_overlap'),
        ),
    ]
