# Generated by Django 5.2.18 on 2026-10-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulechange',
            name='reverts',
            field=models.UUIDField(blank=True, help_text='Set on changes made by undoing another batch.', null=True),
        ),
    ]
